# Generated by Django 4.0.1 on 2022-01-14 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookstoreuser_star_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_stars',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5.0)], verbose_name='stars'),
        ),
        migrations.AddField(
            model_name='bookstoreuser',
            name='review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookstoreuser',
            name='stars',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
